// AUTO-GENERATED by scripts/generate-data.ts — do not edit.
// Run `pnpm generate` to regenerate from full-trip.md.

import type { TripDay } from './types';

export const itinerary: TripDay[] = [
  {
    "day": 1,
    "date": "2026-04-03",
    "dayOfWeek": "Friday",
    "title": "Arrival + Muir Woods",
    "summary": "Arrive in Northern California and ease into the trip with a redwood walk at Muir Woods—one of the last old-growth coastal groves on earth. A gentle first afternoon under the canopy before heading to wine country.",
    "segmentId": "arrival",
    "attire": "Comfortable layers for the redwood trail; smart casual for dinner.",
    "activities": [
      {
        "time": "10:45am–12:15pm",
        "name": "Land at SFO + rental car + lunch to-go",
        "description": "Land at SFO, pick up the rental car, and keep lunch simple (airport or a quick stop in Mill Valley) so you're fueled before the redwoods. This block stays intentionally flexible for baggage, the rental car shuttle, and a quick pharmacy/snack run if you want it.",
        "locationIds": [
          "san-francisco-international-airport-sfo"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~1 hr",
          "from": "SFO",
          "to": "Muir Woods"
        }
      },
      {
        "time": "1:15pm–3:00pm",
        "name": "Muir Woods National Monument (Main Trail)",
        "description": "Walk the mostly flat, shaded Main Trail for an easy introduction to California's coastal redwoods—a short out-and-back or a longer stroll depending on your legs after travel. The grove is one of the last surviving old-growth coastal redwood stands, protected as a national monument in 1908 after a campaign by William Kent, who donated the land specifically to block a dam project. Bring a light layer; it stays cool under the canopy even on warm days.",
        "locationIds": [
          "muir-woods-main-trail",
          "muir-woods-national-monument"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~1 hr",
          "from": "Muir Woods",
          "to": "The Estate Yountville"
        }
      }
    ]
  },
  {
    "day": 1,
    "date": "2026-04-03",
    "dayOfWeek": "Friday",
    "title": "Evening in Yountville",
    "summary": "Settle into Yountville for your first taste of Napa's culinary heart—a relaxed evening to recharge after the travel day.",
    "segmentId": "napa",
    "activities": [
      {
        "time": "4:00pm",
        "name": "Arrive + check-in at The Estate Yountville",
        "description": "Arrive at The Estate Yountville and settle into your King Guestroom on the Vintage Estate, with easy access to the property's gardens, spa/pool, and Yountville's walkable main strip. The Vintage Estate buildings and grounds have that classic Napa feel, and the room's balcony makes a great place to decompress after the travel day. Yountville is Napa's small-town culinary hub, known for its concentration of standout restaurants.",
        "locationIds": [
          "the-estate-yountville"
        ]
      },
      {
        "time": "6:00pm",
        "name": "Dinner at Bottega Napa Valley",
        "description": "Dinner at Bottega, Michael Chiarello's Italian-Californian kitchen—rustic handmade pastas and wood-fired dishes rooted in California produce, rendered through the lens of his Italian heritage. The menu rotates seasonally but stays true to those fundamentals, and the atmosphere is composed without being fussy. Conveniently located right on The Estate property, so there's no car needed after a long travel day.",
        "locationIds": [
          "bottega-napa-valley"
        ]
      }
    ]
  },
  {
    "day": 2,
    "date": "2026-04-04",
    "dayOfWeek": "Saturday",
    "title": "Napa’s Natural Bounty",
    "summary": "Today is Napa at its most farm-to-table—market browsing, an olive oil tasting, a gondola-view winery stop, and a relaxed dinner in St. Helena.",
    "segmentId": "napa",
    "attire": "Comfortable walking shoes for the farmers market and winery; smart casual for dinner at Farmstead.",
    "activities": [
      {
        "time": "9:30am–10:45am",
        "name": "Napa Farmers Market (downtown Napa)",
        "description": "Browse local produce, breads, cheeses, and small artisan vendors at the Napa Farmers Market—a lively, year-round operation and a good snapshot of what's in season in the valley. An easy, open-air stop with plenty of options for tasting and picking up a snack for the road.",
        "locationIds": [
          "napa-farmers-market"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~30 min",
          "from": "downtown Napa",
          "to": "Round Pond (Rutherford)"
        }
      },
      {
        "time": "11:30am–1:00pm",
        "name": "Round Pond: Olive Oil Gourmet Experience",
        "description": "Round Pond is one of only two functioning olive mills in Napa Valley, pressing five Italian and three Spanish olive varieties hand-harvested and cold-pressed on-site at their 468-acre Rutherford estate. The Gourmet Experience is a structured, seated tasting—walked through like a wine tasting, with aroma and palate assessment—paired with seasonal bites from the estate kitchen. It's genuinely educational without being dry, and a nice contrast to the wine tastings surrounding it.",
        "locationIds": [
          "round-pond-estate"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~20 min",
          "from": "Round Pond (Rutherford)",
          "to": "The Estate Yountville"
        }
      },
      {
        "time": "1:00pm",
        "name": "Return to the hotel for lunch + downtime",
        "description": "Head back to Yountville for a simple lunch and a real break in the day. Use this window for pool/spa time, a walk around The Estate, or just getting ready for the afternoon tasting.",
        "locationIds": [],
        "travelAfter": {
          "mode": "drive",
          "duration": "~25 min",
          "from": "The Estate Yountville",
          "to": "Sterling Vineyards (Calistoga)"
        }
      },
      {
        "time": "4:15pm–5:15pm",
        "name": "Sterling Vineyards tasting + gondola ride",
        "description": "Ride the gondola up to Sterling's whitewashed, Mykonos-inspired winery—perched on a 300-foot knoll above Calistoga—for a self-guided tasting of five wines with sweeping valley views. The aerial gondola opened in 1973 as the first at any winery in the world; the current cars were installed after the winery rebuilt following the 2020 Glass Fire. Plan on some walking around the hilltop, so comfortable shoes and a light layer are helpful.",
        "locationIds": [
          "sterling-vineyards"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~20 min",
          "from": "Sterling Vineyards (Calistoga)",
          "to": "Farmstead (St. Helena)"
        }
      },
      {
        "time": "6:00pm",
        "name": "Dinner at Farmstead at Long Meadow Ranch",
        "description": "Farmstead is the restaurant arm of Long Meadow Ranch, whose land dates to an 1872 patent grant signed by Ulysses S. Grant—now a genuinely integrated operation raising grass-fed beef, growing organic produce, and pressing estate olive oil, much of which feeds directly into the kitchen. The food is American farmhouse cooking: live-fire preparations, seasonal vegetables, and ranch-raised proteins, served inside a restored 19th-century barn on Main Street in St. Helena. Polished but relaxed—a good anchor for a long Napa evening.",
        "locationIds": [
          "farmstead-at-long-meadow-ranch"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~15 min",
          "from": "Farmstead (St. Helena)",
          "to": "The Estate Yountville"
        }
      },
      {
        "time": "8:00pm",
        "name": "Return to the hotel",
        "description": "Return to The Estate for an easy wind-down and a good night's sleep.",
        "locationIds": []
      }
    ]
  },
  {
    "day": 3,
    "date": "2026-04-05",
    "dayOfWeek": "Sunday",
    "title": "Napa’s Wine Culture",
    "summary": "Lean into Napa's wine culture with the Oxbow market, the historic Schramsberg caves, and a flexible afternoon before a celebratory dinner.",
    "segmentId": "napa",
    "attire": "Casual layers for wine tastings; pack a sweater for the Schramsberg caves; smart casual for dinner at Ad Hoc.",
    "activities": [
      {
        "time": "9:00am–10:15am",
        "name": "Oxbow Public Market",
        "description": "Make a casual stop at Oxbow for coffee and pastries, plus a few easy tastings. Opened in 2007 as a 40,000-square-foot food hall along the Napa River, it's credited with helping kick-start the revival of downtown Napa as a destination; anchor tenants include Hog Island Oyster Co. (the only Napa outpost of the famous Tomales Bay operation) and a good cheese-and-wine counter. Mostly indoors, easy to navigate, and good for a quick graze or a slower sit by the river.",
        "locationIds": [
          "oxbow-public-market"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~35 min",
          "from": "Oxbow Public Market (Napa)",
          "to": "Schramsberg (Calistoga)"
        }
      },
      {
        "time": "11:00am–12:30pm",
        "name": "Schramsberg Vineyards Cave Tour",
        "description": "Take the classic Schramsberg cave tour—a guided walk through cool underground cellars built by Chinese laborers in the 1860s, with a structured tasting of Schramsberg sparkling and Davies wines plus a cheese and charcuterie accompaniment. Schramsberg was founded in 1862, making it one of Napa's oldest wineries; it earned lasting fame in 1972 when Nixon served its Blanc de Blancs at the historic \"Toast to Peace\" dinner in China. The caves run genuinely chilly year-round, so pack a sweater—and plan for Dan, Jen, and Ava to stay flexible in Yountville while you're on the tour.",
        "locationIds": [
          "schramsberg-vineyards"
        ],
        "subgroup": "Susan + Ted",
        "travelAfter": {
          "mode": "drive",
          "duration": "~35 min",
          "from": "Schramsberg (Calistoga)",
          "to": "The Estate Yountville"
        }
      },
      {
        "time": "1:00pm–5:30pm",
        "name": "Downtime / pool time",
        "description": "Return to The Estate for a true downtime block—massage (if scheduled), pool time, a quiet walk around the property, or simply resting in your room. This is intentionally open so you can adjust based on how you're feeling.",
        "locationIds": [],
        "travelAfter": {
          "mode": "drive",
          "duration": "~5 min",
          "from": "The Estate Yountville",
          "to": "Ad Hoc"
        }
      },
      {
        "time": "5:45pm",
        "name": "Dinner at Ad Hoc",
        "description": "Dinner at Ad Hoc, Thomas Keller's family-style restaurant on Washington Street in Yountville—a deliberately casual counterpart to The French Laundry, serving a single four-course prix fixe menu that changes nightly. The format is communal and generous: big platters of seasonal, comfort-driven cooking served family-style to the table. It's a quintessential Yountville experience and a great celebratory dinner for the whole group before packing up for Yosemite.",
        "locationIds": [
          "ad-hoc"
        ]
      },
      {
        "time": "After dinner",
        "name": "Return to the hotel + pack for Yosemite",
        "description": "Return to The Estate and pack for an early start and a longer drive day, keeping the morning setup easy (layers, comfortable shoes, and snacks/water for the car).",
        "locationIds": []
      }
    ]
  },
  {
    "day": 4,
    "date": "2026-04-06",
    "dayOfWeek": "Monday",
    "title": "To Yosemite + Lodge Settle-In",
    "summary": "Leave wine country behind and head for the Sierra. Rush Creek Lodge is a comfortable base just outside Yosemite’s Big Oak Flat Entrance on CA-120—close enough for an early start tomorrow, but relaxing enough to feel like a destination on its own (pool/hot tubs, fire pits, easy on-property trails).",
    "segmentId": "yosemite",
    "attire": "Comfortable travel clothes for the long drive; casual layers for the lodge and evening walk.",
    "activities": [
      {
        "time": "8:30am–1:00pm",
        "name": "Drive Yountville → Rush Creek Lodge (Yosemite area)",
        "description": "Expect about a 4.5-hour drive that gradually trades vineyard rows for rolling foothills and then piney mountain terrain. A lunch stop in Oakdale or Groveland (both classic Sierra gateway towns) is an easy way to break up the day—and a nice introduction to the region’s Gold Rush and park-gateway history.",
        "locationIds": [
          "rush-creek-lodge-and-spa-at-yosemite",
          "the-restaurant-at-rush-creek"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~4 hr 30 min",
          "from": "Yountville",
          "to": "Rush Creek Lodge"
        }
      },
      {
        "time": "1:00pm",
        "name": "Arrive at Rush Creek Lodge + lunch",
        "description": "Arrive at Rush Creek Lodge and check in. Think “mountain camp, upgraded”: a warm lodge atmosphere, outdoor gathering spots, and just enough nature right on the property to start feeling like you’ve arrived in Yosemite country.",
        "locationIds": [
          "the-restaurant-at-rush-creek",
          "rush-creek-lodge-and-spa-at-yosemite"
        ]
      },
      {
        "time": "5:30pm",
        "name": "Dinner at The Restaurant at Rush Creek",
        "description": "Have dinner on-site—an easy, satisfying basecamp dinner before tomorrow’s Yosemite day. Expect seasonal California-style cooking and plenty of options that work whether you want something hearty or something lighter.",
        "locationIds": [
          "the-restaurant-at-rush-creek",
          "rush-creek-lodge-and-spa-at-yosemite"
        ]
      },
      {
        "time": "Evening",
        "name": "S’mores + fire pits + stargazing",
        "description": "Wrap up the day by walking the property, doing one of the craft activities offered by the hotel, enjoying s'mores at the lodge fire pits while doing a little stargazing.",
        "locationIds": []
      }
    ]
  },
  {
    "day": 5,
    "date": "2026-04-07",
    "dayOfWeek": "Tuesday",
    "title": "Yosemite Valley Highlights",
    "summary": "A Yosemite Valley day built around the classics, structured as one clean west-to-east loop with no backtracking. The Valley's roads are one-way and anticlockwise: you drive in on Southside Drive heading east, stop at Bridalveil and the Village, then return west on Northside Drive on the way out. Expect roughly 3 miles of easy, mostly flat walking spread across the day, with long natural breaks between stops.",
    "segmentId": "yosemite",
    "activities": [
      {
        "time": "8:15am",
        "name": "Drive to Yosemite Valley",
        "description": "Drive into Yosemite Valley as the scenery shifts from forested slopes to sheer granite walls. The Valley is famously glacially carved, which is why it opens up so dramatically and feels built for views.",
        "locationIds": [
          "yosemite-valley"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~45 min",
          "from": "Rush Creek Lodge",
          "to": "Yosemite Valley"
        }
      },
      {
        "time": "9:30am",
        "name": "Tunnel View",
        "description": "Stop at Tunnel View for Yosemite's most famous overlook — El Capitan, Bridalveil Fall, and Half Dome all in one sweep. The viewpoint became iconic after the Wawona Tunnel opened in the 1930s, and it's still the classic \"first big reveal\" spot in the Valley. Tunnel View has its own dedicated parking lot directly at the overlook.",
        "locationIds": [
          "half-dome",
          "bridalveil-fall-trail",
          "tunnel-view"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~5 min",
          "from": "Tunnel View",
          "to": "Bridalveil Fall"
        }
      },
      {
        "time": "10:00am–10:45am",
        "name": "Bridalveil Fall Trail (0.5mi)",
        "description": "Walk the short, mostly paved trail to Bridalveil Fall — 620 feet of free-falling water known to the Valley's Ahwahneechee people as Pohono, \"puffing wind,\" for the way breezes deflect the lower cascade. In April, the flow is typically strong and the mist at the base can be intense; bring a light layer. Bridalveil has its own parking lot right at the trailhead off Southside Drive, just a few minutes east of Tunnel View. If the lot is full, overflow parking is available a few hundred yards further east on Southside Drive.",
        "locationIds": [
          "bridalveil-fall-trail",
          "tunnel-view"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~20 min",
          "from": "Bridalveil Fall",
          "to": "Yosemite Village"
        }
      },
      {
        "time": "11:30am–12:30pm",
        "name": "Lower Yosemite Falls Loop (1mi)",
        "description": "Continue east on Southside Drive to Yosemite Village, where parking is centralized for the next several stops. Do the 1-mile paved loop to Lower Yosemite Fall — easy walking with a huge payoff. Yosemite Falls is the tallest waterfall in North America at 2,425 feet total; the lower fall alone is 320 feet, and spring snowmelt makes it loud, fast, and genuinely misty at close range. Park once at the Village and leave the car here through lunch and the meadow walk.",
        "locationIds": [
          "lower-yosemite-falls-loop",
          "yosemite-village"
        ]
      },
      {
        "time": "1:00pm",
        "name": "Lunch / picnic at Yosemite Village",
        "description": "Take a midday reset with a simple picnic lunch and a wander through Yosemite Village. This is the Valley's historic hub for small exhibits, browsing shops, and soaking in the human side of Yosemite's story alongside the scenery. No driving required — the next two stops are both walkable from here.",
        "locationIds": [
          "yosemite-village",
          "rush-creek-lodge-and-spa-at-yosemite"
        ]
      },
      {
        "time": "2:00pm–2:30pm",
        "name": "Sentinel Bridge",
        "description": "Walk from the Village to Sentinel Bridge — about 5 minutes on foot — for the classic Half Dome viewpoint with the Merced River often adding reflections. It's a longtime photographer favorite, and one of the best spots in the Valley to feel the scale of what's around you without any effort.",
        "locationIds": [
          "sentinel-bridge",
          "merced-river",
          "half-dome"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~45 min",
          "from": "Yosemite Village",
          "to": "Rush Creek Lodge"
        }
      },
      {
        "time": "4:30pm",
        "name": "Arrive at Rush Creek Lodge: pool / hot tubs / deck time",
        "description": "",
        "locationIds": [
          "the-restaurant-at-rush-creek",
          "rush-creek-lodge-and-spa-at-yosemite"
        ]
      },
      {
        "time": "6:00pm",
        "name": "Dinner at The Restaurant at Rush Creek",
        "description": "",
        "locationIds": [
          "the-restaurant-at-rush-creek",
          "rush-creek-lodge-and-spa-at-yosemite"
        ]
      }
    ]
  },
  {
    "day": 6,
    "date": "2026-04-08",
    "dayOfWeek": "Wednesday",
    "title": "To Carmel + Ocean Reset",
    "summary": "A scenery shift day—from granite and pines to ocean cliffs and Pacific air. Arrive in Carmel with enough time to enjoy the coastal sunset and a fresh, local dinner.",
    "segmentId": "carmel",
    "attire": "Comfortable clothes for the drive; casual for dinner in Carmel.",
    "activities": [
      {
        "time": "8:00am",
        "name": "Drive from Rush Creek Lodge to Carmel (route-flex with stops)",
        "description": "Check out and head for the coast, with a handful of optional stops on the way: a quick pause by the Merced River, lunch in Mariposa (a well-preserved Gold Rush–era town), or a walk through Mariposa Grove's giant sequoias. The drive itself gradually trades granite peaks for rolling oak savanna and then the coastal hills—worth treating as a journey, not just transit.",
        "locationIds": [
          "merced-river",
          "rush-creek-lodge-and-spa-at-yosemite",
          "the-restaurant-at-rush-creek"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~6 hr",
          "from": "Rush Creek Lodge",
          "to": "Hyatt Carmel Highlands (with stops)"
        }
      },
      {
        "time": "2:00pm",
        "name": "Arrive + check-in at Hyatt Carmel Highlands",
        "description": "Arrive at Hyatt Carmel Highlands—a clifftop retreat operating in this spot since 1917—and settle into the view: Pacific horizon, rocky coastline, and the kind of \"sit and stare\" atmosphere that makes the coast feel immediately restorative after Yosemite.",
        "locationIds": [
          "hyatt-carmel-highlands"
        ]
      },
      {
        "time": "6:00pm",
        "name": "Casual dinner in Carmel",
        "description": "Drive into Carmel for dinner at Il Tegamino, a small Southern Italian trattoria tucked into the historic Court of the Golden Bough—a courtyard accessible via a passageway off Ocean Avenue—run by Neapolitan chef Giuseppe Panzuto. The menu is comfort-forward: slow-cooked ragus, house-made pastas, and a polpette (meatball) bar that includes a crab version. Cozy and family-run, with courtyard seating among lemon trees—a good, relaxed way to arrive on the coast.",
        "locationIds": [
          "il-tegamino"
        ]
      },
      {
        "time": "Evening",
        "name": "Waves + sunset from the balcony",
        "description": "Keep the evening simple—balcony time, sunset, and an early night after a long drive.",
        "locationIds": []
      }
    ]
  },
  {
    "day": 7,
    "date": "2026-04-09",
    "dayOfWeek": "Thursday",
    "title": "Big Sur on Highway 1",
    "summary": "Spend a full Big Sur day on Highway 1: short coastal hikes at Garrapata, a landmark-rich scenic drive, a scenic lunch, and a redwood river stroll in the afternoon. The Big Sur section of Highway 1—completed in the 1930s—opened this coastline to road travelers, and it still feels like one of the world's great “scenic drive” experiences.",
    "segmentId": "carmel",
    "attire": "Active layers for bluff walks and redwood hikes; smart casual for Pacific's Edge dinner.",
    "activities": [
      {
        "time": "9:30am–11:15am",
        "name": "Garrapata State Park: Soberanes Point + Calla Lily Valley",
        "description": "Start the morning at Garrapata State Park with two short hikes that show off different sides of the coast: first, the Soberanes Point Trail out toward Painter's Point for easy bluff-top views around Garrapata Bluff; then the Garrapata Trail into Calla Lily Valley, where spring usually brings lush greenery and the kind of tucked-away coastal scenery that feels quietly cinematic. It's an active start, but still gentle enough to keep the day feeling relaxed.",
        "locationIds": [
          "garrapata-bluff-trail"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~20 min",
          "from": "Garrapata State Park",
          "to": "Hyatt Carmel Highlands"
        }
      },
      {
        "time": "12:00pm",
        "name": "Brief refresh stop at the hotel + scenic drive south",
        "description": "Return to the hotel for a quick reset, then head back down Highway 1 toward lunch with the route itself as part of the outing. On the drive, take in a string of classic landmarks—Rocky Point, Bixby Creek Bridge, Point Sur Lighthouse, and Andrew Molera State Park—which together capture the full Big Sur rhythm of cliffs, bridges, headlands, and open ocean.",
        "locationIds": [
          "andrew-molera-state-park",
          "point-sur-lighthouse",
          "bixby-creek-bridge",
          "rocky-point",
          "highway-1-big-sur-coast"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~45 min",
          "from": "Hyatt Carmel Highlands",
          "to": "Ventana Big Sur (Sur House, with scenic landmarks)"
        }
      },
      {
        "time": "12:30pm–1:30pm",
        "name": "Lunch at The Sur House at Ventana Big Sur",
        "description": "Have lunch at The Sur House at Ventana Big Sur—a redwood-shaded hillside setting with Pacific air drifting in, which captures Big Sur's \"forest meets ocean\" personality in one spot. The kitchen leans into locally sourced, California-forward cooking in a setting that makes the meal feel like part of the landscape.",
        "locationIds": [
          "ventana-big-sur",
          "the-sur-house"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~10 min",
          "from": "Ventana Big Sur (Sur House)",
          "to": "Pfeiffer Big Sur State Park"
        }
      },
      {
        "time": "2:00pm–2:30pm",
        "name": "Pfeiffer Big Sur State Park: Redwood River Walk",
        "description": "Make a brief stop at Pfeiffer Big Sur State Park for the Redwood River Walk, an easy stretch beneath towering redwoods along the Big Sur River. It's cooler, quieter, and a perfect contrast to the open bluffs and ocean panoramas from earlier in the day.",
        "locationIds": [
          "pfeiffer-big-sur-state-park",
          "pfeiffer-big-sur-redwood-river-walk"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~45 min",
          "from": "Pfeiffer Big Sur State Park",
          "to": "Hyatt Carmel Highlands"
        }
      },
      {
        "time": "2:30pm",
        "name": "Drive back to the hotel: relax time until dinner",
        "description": "Head back to Carmel Highlands and leave the rest of the afternoon open for true downtime—pool time if you want it, a glass of wine at sunset, showers, or simply sitting with the view before dinner.",
        "locationIds": []
      },
      {
        "time": "6:15pm",
        "name": "Dinner at the hotel: Pacific’s Edge (Hyatt Carmel Highlands)",
        "description": "Dinner at Pacific's Edge, the Hyatt's clifftop restaurant at roughly 400 feet elevation with unobstructed sightlines down the Big Sur coastline—the view is the dominant feature of any meal here. The kitchen focuses on seasonal California coastal cooking with an emphasis on local seafood; the wine program has been ranked among Wine Spectator's top 20 in the country. Start with a cocktail on the terrace if weather allows.",
        "locationIds": [
          "pacifics-edge",
          "hyatt-carmel-highlands",
          "highway-1-big-sur-coast"
        ]
      }
    ]
  },
  {
    "day": 8,
    "date": "2026-04-10",
    "dayOfWeek": "Friday",
    "title": "Point Lobos + Carmel + Farewell Dinner",
    "summary": "A coastal favorites day with Point Lobos, Carmel-by-the-Sea, and the 17-Mile Drive, capped by a farewell dinner in Carmel village. It's a relaxed, celebratory wrap for the Monterey Peninsula with plenty of time to pause and enjoy the views.",
    "segmentId": "carmel",
    "attire": "Layers for Point Lobos and the food tour; smart casual for dinner at Mission Bistro.",
    "activities": [
      {
        "time": "8:00am",
        "name": "Point Lobos State Reserve (South Shore Trail route)",
        "description": "Visit Point Lobos—often called the crown jewel of California’s state parks—for a morning of coves, headlands, and constant ocean views. A great route is to park at Piney Woods and connect South Shore Trail → Sand Hill Trail → Sea Lion Point (with the option to add Cypress Grove). Plan on roughly 2–3 miles of easy-to-moderate walking with time built in for wildlife watching (sea lions, seabirds, and often sea otters offshore).",
        "locationIds": [
          "point-lobos-state-reserve",
          "south-shore-trail-point-lobos",
          "sand-hill-trail-point-lobos",
          "sea-lion-point-point-lobos",
          "cypress-grove-trail-point-lobos"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~15 min",
          "from": "Point Lobos",
          "to": "Carmel-by-the-Sea"
        }
      },
      {
        "time": "11:00am–2:00pm",
        "name": "Carmel-by-the-Sea Classic Food Tour",
        "description": "Join a guided walking tour through Carmel's cottage-lined streets, with five or six tastings at local eateries and shops along the way. Stops vary but typically include a wine tasting, a chocolate shop, and a mix of Carmel's better-known and off-the-beaten-path spots—the kind of places you'd otherwise walk right past. The format is small-group and the guide weaves in Carmel's history and architecture as you go: the arts colony roots, the no-traffic-lights-or-streetlights quirks, the European village layout that makes it feel unlike anywhere else in California.",
        "locationIds": [
          "carmel-by-the-sea"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~15 min",
          "from": "Carmel-by-the-Sea",
          "to": "Carmel Highlands"
        }
      },
      {
        "time": "2:15pm",
        "name": "Return to the hotel for rest + balcony downtime + light packing",
        "description": "Go back to the hotel for a real rest block and light packing. It's also a perfect \"sit and look at the ocean\" window—the kind of quiet time that makes the trip feel like a celebration, not a checklist.",
        "locationIds": [],
        "travelAfter": {
          "mode": "drive",
          "duration": "~25 min",
          "from": "Carmel Highlands",
          "to": "Pebble Beach gate"
        }
      },
      {
        "time": "3:30pm",
        "name": "Pebble Beach 17-Mile Drive (golden light loop)",
        "description": "Drive the 17-Mile Drive loop in late-day light—a privately maintained road with a modest entry fee (usually waived with any restaurant stop)—pausing for pull-offs like Lone Cypress (one of the most photographed trees in North America) and the surf break at Spanish Bay. It's a curated coastline loop through forest, rocky shore, and famous golf links, and the late-afternoon light makes it considerably better than a midday drive.",
        "locationIds": [
          "17-mile-drive",
          "pebble-beach",
          "lone-cypress",
          "spanish-bay"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~15 min",
          "from": "Pebble Beach",
          "to": "Mission Bistro (Carmel)"
        }
      },
      {
        "time": "6:00pm",
        "name": "Dinner at Mission Bistro",
        "description": "Head straight from the 17-Mile Drive into Carmel village for dinner at Mission Bistro, a tucked-away dining room on Mission Street that feels very much in keeping with Carmel's understated character: intimate, proprietor-led, and rooted in the village rather than the tourist strip. The menu is a strong fit for the final night on the coast, with Pacific seafood at the center and produce sourced from Monterey and Santa Cruz County farms and ranches, so the meal feels specific to this stretch of California rather than generically celebratory. Reviewers regularly mention owner Shaheen Alnuaimi greeting tables and chef Matt Zimny walking the room, which gives the evening a warm, personal finish for Susan's birthday dinner.",
        "locationIds": [
          "mission-bistro",
          "17-mile-drive"
        ]
      },
      {
        "time": "After dinner",
        "name": "Return to the hotel for a quiet night + packing",
        "description": "Return to the hotel for a quiet evening and packing.",
        "locationIds": []
      }
    ]
  },
  {
    "day": 9,
    "date": "2026-04-11",
    "dayOfWeek": "Saturday",
    "title": "Travel Home",
    "summary": "A simple travel-home day with a calm morning, a straight shot to SFO, and plenty of buffer at the airport. It's an easy finish that keeps the return smooth and stress-free.",
    "segmentId": "carmel",
    "attire": "Comfortable travel clothes for the drive home.",
    "activities": [
      {
        "time": "10:00am",
        "name": "Depart Carmel Highlands",
        "description": "Check out and head to SFO, with one last look at the coastline on the way out.",
        "locationIds": [
          "san-francisco-international-airport-sfo"
        ],
        "travelAfter": {
          "mode": "drive",
          "duration": "~2 hr",
          "from": "Carmel Highlands",
          "to": "SFO"
        }
      },
      {
        "time": "12:00pm",
        "name": "Arrive SFO + return the rental car",
        "description": "Return the car, grab a snack if you want, and head to the gate with plenty of time for security and boarding.",
        "locationIds": [
          "san-francisco-international-airport-sfo"
        ]
      },
      {
        "time": "2:00pm",
        "name": "Flight home",
        "description": "Fly home with big sights, photos and stories from your California journey.",
        "locationIds": []
      }
    ]
  }
];
