// AUTO-GENERATED by scripts/generate-data.ts — do not edit.
// Run `pnpm generate` to regenerate from full-trip.md.

import type { TripMeta } from './types';

export const tripMeta: TripMeta = {
  "title": "Susan’s 70th Birthday",
  "subtitle": "California, USA | April 3-11, 2026",
  "overview": "To celebrate Susan’s 70th, this nine-day California journey blends iconic landscapes with unforgettable food and wine—starting under the redwoods of Muir Woods, easing into Napa and Sonoma’s vineyards, markets, and tastings, then heading into Yosemite for a full day among the Sierra’s granite and forests, and finishing along the Monterey/Carmel coast. It’s a “trip of a lifetime” that honors California’s natural heritage and culinary legacy. Expect standout stays, thoughtful logistics, and a warm, welcoming flow that makes the whole week feel both special and easy.",
  "dates": "April 3-11, 2026",
  "duration": "9 days / 8 nights",
  "flights": {
    "airline": "United Airlines",
    "confirmation": "#CST454",
    "outbound": {
      "number": "UA 369",
      "date": "Fri Apr 3, 2026",
      "departure": "DCA 7:30am EDT",
      "arrival": "SFO 10:42am PDT"
    },
    "return": {
      "number": "UA 2386",
      "date": "Sat Apr 11, 2026",
      "departure": "SFO 2:00pm PDT",
      "arrival": "DCA 10:28pm EDT"
    }
  },
  "dailySchedule": [
    {
      "date": "Fri Apr 3",
      "base": "SFO + Muir Woods",
      "logistics": "Fly DCA → SFO → Drive SFO → Muir Woods → Napa/Sonoma",
      "segmentId": "arrival"
    },
    {
      "date": "Sat Apr 4",
      "base": "Napa / Sonoma",
      "logistics": "Stay Napa/Sonoma",
      "segmentId": "napa"
    },
    {
      "date": "Sun Apr 5",
      "base": "Napa / Sonoma",
      "logistics": "Stay Napa/Sonoma",
      "segmentId": "napa"
    },
    {
      "date": "Mon Apr 6",
      "base": "Yosemite",
      "logistics": "Checkout Napa → Drive Napa → Yosemite → Check-in Yosemite",
      "segmentId": "yosemite"
    },
    {
      "date": "Tue Apr 7",
      "base": "Yosemite",
      "logistics": "Yosemite full day",
      "segmentId": "yosemite"
    },
    {
      "date": "Wed Apr 8",
      "base": "Carmel / Big Sur",
      "logistics": "Checkout Yosemite → Drive Yosemite → Monterey/Carmel → Check-in",
      "segmentId": "carmel"
    },
    {
      "date": "Thu Apr 9",
      "base": "Carmel / Big Sur",
      "logistics": "Stay Carmel / Big Sur",
      "segmentId": "carmel"
    },
    {
      "date": "Fri Apr 10",
      "base": "Carmel / Big Sur",
      "logistics": "Stay Carmel / Big Sur",
      "segmentId": "carmel"
    },
    {
      "date": "Sat Apr 11",
      "base": "Carmel / Big Sur",
      "logistics": "Checkout Carmel / Big Sur → Drive to SFO → Fly home",
      "segmentId": "carmel"
    }
  ],
  "lodgingConfirmations": [
    {
      "name": "The Estate Yountville",
      "dates": "Apr 3–6",
      "address": "6481 Washington St, Yountville, CA 94599, USA",
      "confirmations": [
        "#OB25123113564304"
      ]
    },
    {
      "name": "Rush Creek Lodge and Spa at Yosemite",
      "dates": "Apr 6–8",
      "address": "34001 CA-120, Groveland, CA 95321, USA",
      "confirmations": [
        "#30251B0386853"
      ]
    },
    {
      "name": "Hyatt Carmel Highlands",
      "dates": "Apr 8–11",
      "address": "120 Highlands Drive, Carmel, CA, US, 93923",
      "confirmations": [
        "#62046930 (Dan, Jen, Ava)",
        "#40702652 (Susan & Ted)"
      ]
    }
  ]
};
