// Auto-generated by scripts/fetch-weather.ts — do not edit.
// Run: pnpm weather

import type { WeatherData } from './types';

export const weatherData: WeatherData = {
  "days": [
    {
      "date": "2026-04-03",
      "displayDate": "Apr 3",
      "location": "SF/Napa",
      "high": 68,
      "low": 52,
      "condition": "sunny",
      "source": "average"
    },
    {
      "date": "2026-04-04",
      "displayDate": "Apr 4",
      "location": "Napa",
      "high": 72,
      "low": 54,
      "condition": "sunny",
      "source": "average"
    },
    {
      "date": "2026-04-05",
      "displayDate": "Apr 5",
      "location": "Napa",
      "high": 81,
      "low": 47,
      "condition": "sunny",
      "shortForecast": "Mostly Sunny",
      "source": "forecast"
    },
    {
      "date": "2026-04-06",
      "displayDate": "Apr 6",
      "location": "Yosemite",
      "high": 70,
      "low": 45,
      "condition": "sunny",
      "shortForecast": "Sunny",
      "source": "forecast"
    },
    {
      "date": "2026-04-07",
      "displayDate": "Apr 7",
      "location": "Yosemite",
      "high": 70,
      "low": 44,
      "condition": "sunny",
      "shortForecast": "Sunny",
      "source": "forecast"
    },
    {
      "date": "2026-04-08",
      "displayDate": "Apr 8",
      "location": "Carmel",
      "high": 71,
      "low": 53,
      "condition": "sunny",
      "shortForecast": "Mostly Sunny",
      "source": "forecast"
    },
    {
      "date": "2026-04-09",
      "displayDate": "Apr 9",
      "location": "Carmel",
      "high": 70,
      "low": 52,
      "condition": "thunderstorm",
      "shortForecast": "Chance Light Rain then Slight Chance Showers And Thunderstorms",
      "source": "forecast"
    },
    {
      "date": "2026-04-10",
      "displayDate": "Apr 10",
      "location": "Carmel",
      "high": 69,
      "low": 51,
      "condition": "light-rain",
      "shortForecast": "Light Rain Likely",
      "source": "forecast"
    },
    {
      "date": "2026-04-11",
      "displayDate": "Apr 11",
      "location": "SF",
      "high": 67,
      "low": 52,
      "condition": "sunny",
      "shortForecast": "Mostly Sunny",
      "source": "forecast"
    }
  ],
  "fetchedAt": "2026-04-05T18:55:13.581Z"
};
