// Auto-generated by scripts/fetch-weather.ts — do not edit.
// Run: pnpm weather

import type { WeatherData } from './types';

export const weatherData: WeatherData = {
  "days": [
    {
      "date": "2026-04-03",
      "displayDate": "Apr 3",
      "location": "SF/Napa",
      "high": 68,
      "low": 52,
      "condition": "sunny",
      "source": "average"
    },
    {
      "date": "2026-04-04",
      "displayDate": "Apr 4",
      "location": "Napa",
      "high": 72,
      "low": 54,
      "condition": "sunny",
      "source": "average"
    },
    {
      "date": "2026-04-05",
      "displayDate": "Apr 5",
      "location": "Napa",
      "high": 70,
      "low": 53,
      "condition": "partly-cloudy",
      "source": "average"
    },
    {
      "date": "2026-04-06",
      "displayDate": "Apr 6",
      "location": "Yosemite",
      "high": 62,
      "low": 38,
      "condition": "partly-cloudy",
      "source": "average"
    },
    {
      "date": "2026-04-07",
      "displayDate": "Apr 7",
      "location": "Yosemite",
      "high": 64,
      "low": 40,
      "condition": "sunny",
      "source": "average"
    },
    {
      "date": "2026-04-08",
      "displayDate": "Apr 8",
      "location": "Carmel",
      "high": 71,
      "low": 51,
      "condition": "sunny",
      "shortForecast": "Sunny",
      "source": "forecast"
    },
    {
      "date": "2026-04-09",
      "displayDate": "Apr 9",
      "location": "Carmel",
      "high": 70,
      "low": 53,
      "condition": "fog",
      "shortForecast": "Patchy Fog then Partly Sunny",
      "source": "forecast"
    },
    {
      "date": "2026-04-10",
      "displayDate": "Apr 10",
      "location": "Carmel",
      "high": 69,
      "low": 51,
      "condition": "thunderstorm",
      "shortForecast": "Showers And Thunderstorms Likely",
      "source": "forecast"
    },
    {
      "date": "2026-04-11",
      "displayDate": "Apr 11",
      "location": "SF",
      "high": 64,
      "low": 50,
      "condition": "thunderstorm",
      "shortForecast": "Showers And Thunderstorms Likely",
      "source": "forecast"
    }
  ],
  "fetchedAt": "2026-04-08T07:45:31.740Z"
};
